### PR TITLE
Issue #98 Stop CaptureBoulder Command

### LINKED ISSUE #98: Ability to cancel auto-boulder-cature
Add an ability to press a button on the joystick and cancel a running `CaptureBoulder` command

### PR DESCRIPTION
**Pull request by JCharante**
closes #98

### CODE REVIEW

**Comment by rtfoley** [comment]
Thinking about this more, we could just make this a StopIntake command where the execute method just sets the intake speed to 0.

Regardless, you can probably just return true from isFinished, and not need the 'finished' variable.

**Comment by wilstenholme** [comment]
`StopCaptureBoulder` is working

**Comment by rtfoley** [comment]
Waiting to merge until tested.

**Comment by wilstenholme** [comment]
Changing command execution to toggleWhenPressed() for `CaptureBoulder`. Deprecating this pull request (see f324523).

**Pull request closed without merging**
