### PR TITLE
Include Utils package - Fix #8

### LINKED ISSUE #8: Add common utility classes from 2015
Bring the following classes/ code from 2015 into the 2016 code under a new 'utils' package:
- Gamepad
- Util class (rename to 'helpers')
  - Add the 'LogAction' method from OutlierCommand into this class

### PR DESCRIPTION
**Pull request by wilstenholme**
Create basic Gamepad and Helpers (with LogAction()) classes

### CODE REVIEW

**Comment by rtfoley** [comment]
I think this looks good, assigning to @BenBernardCIS for 2nd review.

**Comment by wilstenholme** [comment]
Enum values are added, two buttons are renamed for clarification.

**Comment by rtfoley** [comment]
@wilstenholme I would actually leave the LEFT_STICK and RIGHT_STICK names as they were. I think they are clearer than LEFT_BUTTON and RIGHT_BUTTON, since the buttons being referred to really are the sticks themselves (and LEFT_BUTTON might be confusing alongside LB)

**Comment by rtfoley** [comment]
Looking again, we may want to rename LB/ RB to LEFT_BUMPER and RIGHT_BUMPER, for additional clarity though (more descriptive than 'LB').

**Comment by rtfoley** [comment]
Sorry, few more things:
- Rename the methods in the enums to 'getNumber', since the 'axis'/'button' is redundant, and 'value' might suggest that it's return the actual real-time value of the control as opposed to it's location number
- Update Line 74 of the getRawAxis method to pass axis.getNumber() instead of axis.ordinal()
  `
  return super.getRawAxis(axis.getNumber());
  `
- Increase the button enum numbers by one, so that line 83 can just be as follows (without the '+1')
  `
  return super.getRawButton(button.getNumber());
  `

**Comment by rtfoley** [comment]
Looks good to me, @BenBernardCIS?

**Comment by BenBernardCIS** [comment]
Yep, looks good.

**Pull request merged**
